# Generated by Django 2.2 on 2020-01-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='customuser',
            name='boss',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_group',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
